#executar docker compose para subir banco
#Este docker compose monta o arquivo devbook.sql e executa via command.
#Docker commands to solve issues:configs:
#sudo aa-remove-unknown  // removes uknow packages from snap..  dont use
#sudo netstat -nlpt |grep 3306
#sudo kill `sudo lsof -t -i:3306`
#Remove Images:  docker rmi <imageid>

#To rebuild use this command
#docker-compose up --build --force-recreate --no-deps -d db



#   docker system prune -a     - removes all images
version: '3.9'
services:
  db:
    image: db-jmsocial:latest
    command: mysqld --user=root
    container_name: db-jmsocial
    restart: always
    environment:
      MYSQL_DATABASE: 'jmsocial'
      MYSQL_USER: 'jmsocial'

      MYSQL_PASSWORD: 'pwd@123'

      MYSQL_ROOT_PASSWORD: 'pwd@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'

    volumes:
      - my-db:/var/lib/db-jmsocial
      - "./jmsocial.sql:/docker-entrypoint-initdb.d/jmsocial.sql"
    
volumes:
  my-db:
  


