#executar docker compose para subir banco
#Este docker compose monta o arquivo jmsocial.sql e executa via command.
#Docker commands to solve issues:configs:
#sudo aa-remove-unknown  // removes uknow packages from snap..  dont use
#sudo netstat -nlpt |grep 3306
#sudo kill `sudo lsof -t -i:3306`
#Remove Images:  docker rmi <imageid>

#To rebuild use this command
#docker-compose up --build --force-recreate --no-deps -d db

#DUPM OF DATABASE:      mysqldump -u root -ppwd@123 jmsocial >/docker-entrypoint-initdb.d/jmsocial.sql


#   docker system prune -a     - removes all images


# docker run --name mysql -e MYSQL_ROOT_PASSWORD=pwd@123 -d mysql:tag


version: '3.9'
services:
  db:
    image: mysql:latest
    command: mysqld --user=root
    container_name: jmsocial-db
    restart: always
    environment:
      MYSQL_DATABASE: 'jmsocial'
      MYSQL_USER: 'jmsocial'

      MYSQL_PASSWORD: 'pwd@123'

      MYSQL_ROOT_PASSWORD: 'pwd@123'
    ports:
      - '3306:3306'
    expose:
      - '3306'

    volumes:
      - my-db:/var/lib/mysql-dk-xs3x-jm
      - "./jmsocial.sql:/docker-entrypoint-initdb.d/jmsocial.sql"
    
volumes:
  my-db:
  


